name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-and-typecheck-web:
    name: Lint & Type Check (Web)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm --filter web lint

      - name: Type check
        run: pnpm --filter web type-check

  test-web:
    name: Test (Web)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm --filter web test

  lint-and-test-api:
    name: Lint & Test (API)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        working-directory: apps/api
        run: |
          pip install -r requirements.txt

      - name: Lint with Ruff
        working-directory: apps/api
        run: |
          ruff check .

      - name: Run tests
        working-directory: apps/api
        run: |
          pytest

  build-docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck-web, test-web, lint-and-test-api]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Web Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/web/Dockerfile
          push: false
          tags: student-spending-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build API Image
        uses: docker/build-push-action@v5
        with:
          context: apps/api
          file: apps/api/Dockerfile
          push: false
          tags: student-spending-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
